kind: Deployment
apiVersion: apps/v1
metadata:
   name: sagar
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: sagar
   template:
      metadata:
        labels:
          app: sagar
      spec:
       containers:
        - name: sagar
          image: sagarkatale/pipelineprojectnew
          imagePullPolicy: Always
          ports:
          - containerPort: 80
