kind: Service                             
apiVersion: v1
metadata:
  name: sagar
  labels:
    app: sagar
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: sagar                    
  type: LoadBalancer          
